apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    version: v3

  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: scaydogdu/reverseproxy
          name: reverseproxy
          terminationMessagePath: "/tmp/my-log"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
